### ISSUE TITLE
Easify Bug 

### ISSUE THREAD

**Issue by ayush-chouksey** [Spectrum-Beta/HTML-Snippets#1] opened 2020-07-28 12:52 UTC
Issue Type: <b>Feature Request</b>

html intellisence is not working

Extension version: 1.1.6
VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.18362

**Comment by ayush-chouksey** [comment] 2020-07-28 12:55
in my vs code HTML IntelliSense is not working, what is the solution of this issue.

**Comment by AKrisGithub** [comment] 2020-07-29 18:35
Hello There

First of all I'm sorry for the inconvenience it may have caused. Please
make sure of the following :

You've installed the extension properly while you were downloading it.

Also make sure that the Html And  css Intellisense folder can be located in
your workstations vs code extension folder which can be found by digging
into the program files . I'd recommend you to go through the following
article on how to locate the folder :

https://stackoverflow.com/questions/40080793/is-there-a-way-to-change-the-extensions-folder-location-for-visual-studio-code

If there is any errors or mistake in the extensions code ill fix and
address the issue in v1.1.7 ( which will be out in 30 minutes from this
email being sent)

Thank you for addressing the issue.

**Comment by AKrisGithub** [comment] 2020-07-29 18:57
Hi Ayush 

I've looked into it and i haven't found any issues or corrupted files in the primary code and I've even tested it on my local machine ( I haven't experienced any issues ). Could you please specify the exact issue your facing. I'll drop v1.1.7 in about 10 minutes and please check if it addressed your issue. a screenshot or any other piece of info about your issue would be useful. I've attached a screenshot of the extension working as intended as proof.


![Github](https://user-images.githubusercontent.com/52623361/88841731-69c30980-d1ef-11ea-9151-c89ceadfed96.PNG)


- Thank You

**Comment by AKrisGithub** [comment] 2020-07-29 19:05
This Is Just a hypothesis, Maybe you might have disabled emet. The issue is clearly from your side, Please provide me with a solid piece of info for me to look into your issue and to fix it once and for all

**Comment by AKrisGithub** [comment] 2020-07-29 19:09
The Vs Code version and the extension version is compatible since the extension can work in the vs code version 1.45.0. I cant exactly pinpoint your issue and the windows version is not a influencer at all.

**Comment by AKrisGithub** [comment] 2020-07-29 19:15
I've packaged V1.1.7  please update to the latest version.

**Comment by AKrisGithub** [comment] 2020-07-29 19:48
This Is Out Of Topic, I Don't Think This Will Fix Your Issue And I Don't Recommend It If You Don't Want To. Why Don't You Try To Update Windows 10 Version 1903 To Windows 10 Version 2004 ( I Don't Recommend It By All Means Its All Up To You And I Don't Think  Updating Will Make A Difference. The Issue Is Probably Something To Do With Vs Code )

**Comment by Spectrum-Beta** [comment] 2020-07-29 19:56
The Mapping API Will Create The DPS Software

**Comment by Spectrum-Beta** [comment] 2020-07-30 08:26
Ayush ?

**Comment by AKrisGithub** [comment] 2020-07-31 18:04
I Might Have To Close This Issue If You Don't Respond Any Further. Or I Might Have To Consider This As False Complaint.

**Closed as completed** 2020-08-08 16:14 UTC
